name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  lint-and-test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'

      - name: Install dependencies
        run: npm install
  
      - name: Run linting and tests
        run: npm run lint && npm test
